CDD-3357: Upgrade auth-client to 5.6.0
hmrc/customs-dit-licences pull request #29
Opened 2021-09-10 10:16 UTC by lukastymo

All the tests test libraries had to be updated because scala test plus and mockito changed some packages for MockitoSugar. Also, the pegDown needs to be on the classpath now

2021-09-10 11:56 UTC, paulblakehmrc requested changes
There are a few compiler warnings - it's best to reduce or eliminate them as much as possible.

2021-09-10 11:56 UTC, paulblakehmrc commented on project/AppDependencies.scala
> +  val pagDown = "com.vladsch.flexmark" % "flexmark-profile-pegdown" % pegDownVersion % testScope
spelling - `pegDown`

2021-09-13 10:43 UTC, lukastymo commented on project/AppDependencies.scala
> +  val pagDown = "com.vladsch.flexmark" % "flexmark-profile-pegdown" % pegDownVersion % testScope
done

2021-09-13 10:44 UTC, lukastymo commented
I eliminated the warnings + I added `-Xfatal-warnings` for the future.

2021-09-13 11:10 UTC, paulblakehmrc requested changes

2021-09-13 11:10 UTC, paulblakehmrc commented on app/uk/gov/hmrc/customs/dit/licence/connectors/PublicNotificationServiceConnector.scala
> +    logger.debug(s"$msg at $url with\nheaders=${hc.headers(HeaderNames.explicitlyIncludedHeaders)} and\npayload=$payloadAsJsonString publicNotificationRequest")
Is this debug of headers going to to dump everything? I don't think so. Maybe just `{hc}` would get everything?

2021-09-13 11:20 UTC, lukastymo commented on app/uk/gov/hmrc/customs/dit/licence/connectors/PublicNotificationServiceConnector.scala
> +    logger.debug(s"$msg at $url with\nheaders=${hc.headers(HeaderNames.explicitlyIncludedHeaders)} and\npayload=$payloadAsJsonString publicNotificationRequest")
no, not everything. I can use hc as you suggested. I think it will be noisy but it's debug so make sense to see what's there

2021-09-13 11:28 UTC, paulblakehmrc approved these changes

2021-09-13 12:31 UTC, merged